#pragma once

// GLOBAL CONFIGURATION

#define DEFAULT_BLOCKS_PER_GRID 8192
#define THREADS_PER_BLOCK 256
#define DEFAULT_BATCHES_PER_KERNEL 8
#define BATCH_SIZE 16 

#define MAX_PREFIXES 10
#define MAX_PREFIX_LEN 16
